#ifndef ASSET_HEADER_H
#define ASSET_HEADER_H
//NOTE(EVERYONE): This header file was generated by the AssetBuilder

#define INVALID_MESH_ID ((mesh_asset_id)-1)

enum mesh_asset_id
{
	MESH_ASSET_ID_FLOOR,
	MESH_ASSET_ID_PLAYER,
	MESH_ASSET_ID_BOX,
	MESH_ASSET_COUNT
};

#endif
